### ISSUE TITLE
id setting in oracle_select_pad.py

### ISSUE THREAD

**Issue by 1029694141** [potsawee/longsum0#3]
hello ！i want to reproduce your work in arxiv dataset 
when  i  in the ORACLE processing i met some trouble： in  Spotify Podcast dataset we set many ids but in arxiv dataset not ，thus how can i set start id and end id in oracle_select_pad.py ？
thanks for your replying ！

**Comment by 1029694141** [comment]
@potsawee

**Comment by potsawee** [comment]
Hi @1029694141,

1) For **podcast data**, IDs are according to the metadata file from Spotify, e.g. using this code (in `data/podcast_processor.py`) below.

```
    metadata = pandas.read_csv(METADATA_PATH, sep='\t')
    podcasts  = [None for _ in range(end_id-start_id)]
    print("id = [{},{})".format(start_id, end_id))
    for jj, id in tqdm(enumerate(range(start_id, end_id))):
        show_id          = metadata['show_uri'][id].split(':')[-1]
```

2) For **arxiv & pubmed** data, IDs are according to the order as in the text file that you download the data from [this repo](https://github.com/armancohan/long-summarization). For example, first line = id0, second line = id1, etc & you can see the code (in `data/arxiv_processor.py`) below.

```
    with open(load_path) as f:
        lines = f.readlines()
    print("len(data):", len(lines))
    articles = [None for _ in range(len(lines))]
    for i, line in tqdm(enumerate(lines)):
        item = json.loads(line)
        article_id = item['article_id']
```

*** Note that I also include IDs as well as their corresponding `article_id` in the following format [(Download link)](https://drive.google.com/file/d/116Hw7aWp13AU3K65Bu0jzxgOMOSplT4B/view?usp=sharing):

```
ID       article_id
0       1009.3123
1       1512.09139
2       0909.1602
3       1512.03812
4       1512.09024
5       0807.5065
6       0908.1812
7       hep-ph0701277
8       1311.0649
9       nlin0001046
...
```

3. As for setting `start_id` & `end_id`, you can just start from 0 and end at dataset_size (or any interval that you would like). I did this so that I can parallelise the run, e.g. task1 = [0,1000), task2 = [1000,2000), etc.
 
I hope this helps!

**Comment by 1029694141** [comment]
Thank you very much for your answer, it is very helpful.
