### ISSUE TITLE
ValueError: not enough values to unpack (expected 6, got 5)

### ISSUE THREAD

**Issue by 1029694141** [potsawee/longsum0#5]
https://github.com/potsawee/longsum0/blob/436fd7a0732ba5b4e9df46340c4da2c7fc0722f3/train/batch_helper.py#L378

Missing return value：ext_label

**Comment by 1029694141** [comment]
@potsawee

**Comment by potsawee** [comment]
Hi @1029694141 

Thanks for checking out this repo and reporting issue.

I've fixed the issue, please see ```train/batch_helper.py```. Please note that you have two options in running experiments involved hierarchical models:
- ***Option1*** Use seq-to-seq task only (without extractive label). In this case you would only need 5 values returned from the above function. And you can modify other parts accordingly.
- ***Option2*** Use seq-to-seq task & extractive labelling task (multitask learning). In this case you need all 6 values from the function above. Now it's fixed and it should return all necessary values. However, in order to use extractive label information, you need to do more data processing (i.e. computing 'pseudo' extractive label) --- I've shown an example how to do this in ```data/create_extractive_label_example.ipynb```.

Let me know if you have issues here! (I will leave this issue open for the time being)
