### ISSUE TITLE
AttributeError: 'ResearchArticle' object has no attribute 'ext_label'

### ISSUE THREAD

**Issue by 1029694141** [potsawee/longsum0#7]
https://github.com/potsawee/longsum0/blob/06a981576331f44cc6bf29045cb7021efe646ee7/train/batch_helper.py#L242

Hi，when i run ：
 python train/train_hiermodel.py conf/hiermodel_v1.txt

then：
Shuffle data...
Traceback (most recent call last):
  File "train/train_hiermodel.py", line 265, in <module>
    run_training(sys.argv[1])
  File "train/train_hiermodel.py", line 105, in run_training
    input, u_len, w_len, target, tgt_len, ext_target = batcher.get_a_batch(batch                                                                                                      _size)
  File "/home/WwhStuGrp/yyfwwhstu16/longsum/train/batch_helper.py", line 351, in                                                                                                       get_a_batch
    positive_postions = [pi for pi in self.articles[self.cur_id].ext_label if pi                                                                                                       < self.num_utterances]
AttributeError: 'ResearchArticle' object has no attribute 'ext_label'

Thanks for ur replying！@potsawee

**Comment by potsawee** [comment]
Hi @1029694141 ,

Sorry for the poor code design. The error occurs because you load original arxiv/pubmed data instead of arxiv/pubmed with Extractive Labels.

To obtain arxiv/pubmed with extractive labels, please look at the examples in [this notebook](https://github.com/potsawee/longsum0/blob/main/data/create_extractive_label_example.ipynb).

Basically, you have to process the original data (e.g. `data`) to get data with extractive labels (e.g. `data_xtras`). This process can be applied to podcast/arxiv/pubmed. You can do this processing in parallel to speed up.

Once you process the data to have extractive labels to put them into a pickle file, you then set `data_dir` to where the new data is. For example:

from `arxiv/arxiv_{train/dev/train}.pk.bin` to `arxiv/with_ext_label/arxiv_{train/dev/train}.pk.bin`

I hope this helps.

Best wishes,
Potsawee

**Comment by 1029694141** [comment]
Thank you very much for your timely and important reply！

I follow your steps and set new data_dir 

but met  variable error :

Shuffle data...
Traceback (most recent call last):
  File "train/train_hiermodel.py", line 265, in <module>
    run_training(sys.argv[1])
  File "train/train_hiermodel.py", line 105, in run_training
    input, u_len, w_len, target, tgt_len, ext_target = batcher.get_a_batch(batch_size)
  File "/home/WwhStuGrp/yyfwwhstu16/longsum/train/batch_helper.py", line 352, in get_a_batch
    ext_target[batch_count][positive_postions] = 1.0
UnboundLocalError: local variable 'ext_target' referenced before assignment

if we need to set 'ext_target' as global variable?

Thank you again for your help！

**Comment by potsawee** [comment]
Hi @1029694141 ,

Sorry for this late reply. I hope you have resolved the issue on your local copy. Not sure about the issue as I cannot reproduce the error you mention.

The variable ```ext_target``` is defined in line 333, e.g. [```ext_target[batch_count][positive_postions] = 1.0```](https://github.com/potsawee/longsum0/blob/3a182d2c04ddb5179c1d95154e4669a1f8a344c9/train/batch_helper.py#L333) before it is called later. And it is _not_ set as a global variable.

You might want to double check if there is any change in your local copy of code.

**Comment by 1029694141** [comment]
Very good and timely answer!
