### ISSUE TITLE
KeyError: 'ext_labeller'

### ISSUE THREAD

**Issue by 1029694141** [potsawee/longsum0#8]
Hi potsawee!
At inference state:
python decode/inference_hiermodel.py

Traceback (most recent call last):
  File "decode/inference_hiermodel.py", line 266, in <module>
    inference_hiermodel(args)
  File "decode/inference_hiermodel.py", line 52, in inference_hiermodel
    ext_labeller_state_dict = state['ext_labeller']
KeyError: 'ext_labeller'

Thank you for your kind reply and wish you all the best!

**Comment by potsawee** [comment]
Hi @1029694141,

The error is because you use `inference_hiermodel.py` with `--inference_mode` being set to `ext` or `mcs`, but the model that you load was trained in `attn` mode.

If you use download the hierarchical models for arxiv and pubmed from the homepage, they are meant to be use in `attn` mode. Please refer to [this issue](https://github.com/potsawee/longsum0/issues/6) for the hierarchical model in the `mcs` mode.

Hope this helps,
Potsawee
